<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b43d904a-ad43-47c1-8a4b-c17b5239e4dc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.41.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>

</Project>
